// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIKNsC3_94qsI7kuXYybfv3bJS1cHKwA',
    appId: '1:387616541077:web:946d0a0c9a749e40158e9c',
    messagingSenderId: '387616541077',
    projectId: 'task-app-824e4',
    authDomain: 'task-app-824e4.firebaseapp.com',
    storageBucket: 'task-app-824e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdpQKYrRnP5FpfrhXHHxlUgJXHS0NnWsg',
    appId: '1:387616541077:android:f91565ad29f355f9158e9c',
    messagingSenderId: '387616541077',
    projectId: 'task-app-824e4',
    storageBucket: 'task-app-824e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFRFUD1z7Ljdgg3GxZ2eOJedkoMrwIy1Y',
    appId: '1:387616541077:ios:60edd0986ff3b159158e9c',
    messagingSenderId: '387616541077',
    projectId: 'task-app-824e4',
    storageBucket: 'task-app-824e4.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFRFUD1z7Ljdgg3GxZ2eOJedkoMrwIy1Y',
    appId: '1:387616541077:ios:60edd0986ff3b159158e9c',
    messagingSenderId: '387616541077',
    projectId: 'task-app-824e4',
    storageBucket: 'task-app-824e4.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOIKNsC3_94qsI7kuXYybfv3bJS1cHKwA',
    appId: '1:387616541077:web:797d4527d7400977158e9c',
    messagingSenderId: '387616541077',
    projectId: 'task-app-824e4',
    authDomain: 'task-app-824e4.firebaseapp.com',
    storageBucket: 'task-app-824e4.firebasestorage.app',
  );
}
